package aplicacion.modelo.dominio;
// Generated 26/06/2019 21:52:25 by Hibernate Tools 4.3.1



/**
 * Categorias generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer idcategoria;
     private String nombre;
     private String descripcion;
     private Boolean estado;

    public Categoria() {
    }

    public Categoria(String nombre, String descripcion, Boolean estado) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.estado = estado;
    }
   
    public Integer getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(Integer idcategoria) {
        this.idcategoria = idcategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


